vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /upload/avatars
            upload_destination: '%kernel.project_dir%/public/upload/avatars'
            namer: vich_uploader.namer_uniqid
